# server
server.address=0.0.0.0
server.port=${SERVER_PORT}
spring.application.name=mobinogi
# mysql database connection
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
spring.datasource.url=${SPRING_DATASOURCE_URL}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD}
# hibernate properties
spring.jpa.database-platform=org.hibernate.dialect.MySQLDialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
# google api
google.sheets.credentials.path=${GOOGLE_SHEETS_CREDENTIALS_PATH}
google.sheets.id=${GOOGLE_SHEETS_ID}
# distributed processing
server.instance.id=${INSTANCE_ID:0}
server.total.instances=${TOTAL_INSTANCES:1}
